# Generated by Django 3.2.23 on 2024-03-17 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FishMarketModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.IntegerField()),
                ('length1', models.IntegerField()),
                ('length2', models.IntegerField()),
                ('length3', models.IntegerField()),
                ('height', models.IntegerField()),
                ('width', models.IntegerField()),
            ],
        ),
    ]
